class ModifierAttributes:
    attack = 'attack'
    magic_attack = 'magic_attack'
    defense = 'defense'
    magic_defense = 'magic_defense'
    heal = 'heal'
    life = 'life'
    luck = 'luck'
    critical_percentage = 'critical' # critical_damage
    critical_percentage_reduction = 'critical_reduction'
    attack_percentage = 'attack_percentage'
    skill_damage_percentage = 'skill_damage_percentage'
    single_target_skill_damage_percentage = 'single_target_skill_damage_percentage'
    multi_target_skill_damage_percentage = 'multi_target_skill_damage_percentage'
    normal_attack_damage_percentage = 'normal_attack_damage_percentage'
    penetration_percentage = 'penetration_percentage'
    magic_penetration_percentage = 'magic_penetration_percentage'
    battle_damage_percentage = 'battle_damage_percentage'
    battle_damage_reduction_percentage = 'battle_damage_reduction_percentage'
    magic_attack_percentage = 'magic_attack_percentage'
    defense_percentage = 'defense_percentage'
    magic_defense_percentage = 'magic_defense_percentage'
    damage_percentage = 'damage_percentage'
    damage_reduction_percentage = 'damage_reduction_percentage'
    active_damage_percentage = 'active_damage_percentage'
    counterattack_damage_percentage = 'counterattack_damage_percentage'
    magic_damage_percentage = 'magic_damage_percentage'
    magic_damage_reduction_percentage = 'magic_damage_reduction_percentage'
    heal_percentage = 'heal_percentage'
    life_percentage = 'life_percentage'
    luck_percentage = 'luck_percentage'
    critical_damage_percentage = 'critical_damage_percentage'
    critical_damage_reduction_percentage = 'critical_damage_reduction_percentage'
    fixed_damage_reduction_percentage = 'fixed_damage_reduction_percentage'
    move_range = 'move_range'
    attack_range = 'attack_range'
    absolute_defense_range = 'absolute_defense_range'
    counterattack_first_limit = 'counterattack_first_limit'

    element_attacker_multiplier = 'element_attacker_multiplier'
    element_defender_multiplier = 'element_defender_multiplier'

    is_passives_disabled = 'passives_disabled'
    is_action_disabled = 'action_disabled'
    is_counterattack_disabled = 'counterattack_disabled'
    is_counterattack_first = 'counterattack_first'

